[package]
name = "XWorld"
version = "1.0.0"
authors = []

[addresses]
user_profile = "-"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "devnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]
